apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: mon-app-template # Nom plus pertinent
spec:
  # Liste des paramètres dont on a besoin pour un push
  params:
    - name: gitrepositoryurl
    - name: image-reference
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: full-cicd-pipeline-run-
      spec:
# Étape A: On pointe vers le bon pipeline
        pipelineRef:
          name: full-cicd-pipeline
# Étape B: On utilise les bons paramètres
        params:
        - name: repo-url
          value: $(tt.params.gitrepositoryurl)
        - name: image-reference
          value: $(tt.params.image-reference)
# Étape C: On utilise les bons workspaces
        workspaces:
        - name: shared-data
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi
        - name: docker-credentials
          secret:
            secretName: docker-credentials
